"""
scripts.test_cv_corpus
======================

Batch-runs `agents.cv_validator.validate_cv` over every PDF in a directory
(default: `test_cvs/`) and writes a Markdown compatibility report to
`docs/CV_COMPATIBILITY.md`.

Usage
-----
  # Put diverse CVs into ./test_cvs/ — recommended mix:
  #   - latex_moderncv.pdf
  #   - canva_designer_2col.pdf
  #   - word_ats_template.pdf
  #   - overleaf_academic.pdf
  #   - nonenglish_sample.pdf
  #   - scanned_screenshot.pdf     (expect block)
  #   - password_protected.pdf     (expect block)
  #   - very_short_portfolio.pdf   (expect warn)

  python scripts\\test_cv_corpus.py
  python scripts\\test_cv_corpus.py test_cvs\\   docs\\CV_COMPATIBILITY.md

Why
---
Your only ground-truth is a handful of CVs from one author. The app is
deployed to strangers. This script gives you a repeatable harness to
drop new CV formats into, see exactly how the validator treats them,
and spot regressions before they hit users.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import List

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.cv_validator import validate_cv, ValidationReport  # noqa: E402


DEFAULT_CORPUS_DIR = "test_cvs"
DEFAULT_REPORT     = os.path.join("docs", "CV_COMPATIBILITY.md")


def _row(path: str, r: ValidationReport) -> str:
    name    = os.path.basename(path)
    status  = "✓ pass"  if r.ok and not r.warnings else \
              "⚠ warn"  if r.ok                    else \
              "✗ block"
    errors_s   = "<br>".join(_short(e) for e in r.errors)   or "—"
    warnings_s = "<br>".join(_short(w) for w in r.warnings) or "—"
    d = r.details
    details_s = (
        f"pages={d.get('page_count','?')}, "
        f"chars={d.get('char_count','?')}, "
        f"sections={d.get('section_hits','?')}, "
        f"bullets={d.get('bullet_count','?')}, "
        f"ascii={d.get('ascii_ratio','?')}"
    )
    return (
        f"| `{name}` | {status} | {r.score} | {errors_s} | "
        f"{warnings_s} | {details_s} |"
    )


def _short(msg: str, n: int = 140) -> str:
    msg = str(msg).replace("\n", " ").replace("|", "\\|")
    if len(msg) <= n:
        return msg
    return msg[: n - 1] + "…"


def run(corpus_dir: str, report_path: str) -> int:
    if not os.path.isdir(corpus_dir):
        print(
            f"Corpus directory not found: {corpus_dir}\n"
            f"Create it and drop diverse CV PDFs into it first. "
            f"See module docstring for the recommended mix."
        )
        return 1

    pdfs = sorted(Path(corpus_dir).glob("*.pdf"))
    if not pdfs:
        print(f"No PDFs found in {corpus_dir}.")
        return 1

    rows: List[str] = []
    summary = {"pass": 0, "warn": 0, "block": 0}
    for pdf in pdfs:
        r = validate_cv(str(pdf))
        rows.append(_row(str(pdf), r))
        if not r.ok:
            summary["block"] += 1
        elif r.warnings:
            summary["warn"] += 1
        else:
            summary["pass"] += 1
        print(f"  {pdf.name:40s}  score={r.score:3d}  "
              f"errs={len(r.errors)}  warns={len(r.warnings)}")

    header = [
        "# CV Compatibility Report",
        "",
        "Auto-generated by `scripts/test_cv_corpus.py`. Re-run after adding "
        "new PDFs to `test_cvs/`.",
        "",
        f"- **Total**: {len(pdfs)}",
        f"- **Pass**:  {summary['pass']}",
        f"- **Warn**:  {summary['warn']}",
        f"- **Block**: {summary['block']}",
        "",
        "| File | Status | Score | Errors | Warnings | Details |",
        "|------|--------|-------|--------|----------|---------|",
    ]
    body = header + rows + [
        "",
        "## Legend",
        "- **✓ pass** — CV is fully supported. Expect in-place layout edits.",
        "- **⚠ warn** — CV will run but may fall back to ReportLab rebuild. "
        "Visual fidelity reduced.",
        "- **✗ block** — CV cannot be processed. Fix the reported issue and re-upload.",
    ]

    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(body) + "\n")
    print(f"\nWrote {report_path}  ({summary}).")
    return 0


if __name__ == "__main__":
    corpus = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CORPUS_DIR
    report = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_REPORT
    sys.exit(run(corpus, report))
